### ISSUE TITLE
Previewing data via datastore

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Previewer#18]
This activity XML from the datastore:

http://datastore.iatistandard.org/api/1/access/activity.xml?iati-identifier=NL-KVK-27327087-6505

does not seem to preview:

http://preview.iatistandard.org/index.php?url=http%3A%2F%2Fdatastore.iatistandard.org%2Fapi%2F1%2Faccess%2Factivity.xml%3Fiati-identifier%3DNL-KVK-27327087-6505

To do with the `<result>` element in the datastore XML?

Is there any way around this @Bjwebb @caprenter

**Comment by Bjwebb** [comment]
> To do with the `<result>` element in the datastore XML?

Yes.

The previewer could be modified to work with this.

**Comment by caprenter** [comment]
The datastore XML will not validate as IATI compliant XML - as it has this additional information in it - see also the query fields.

The previewer isn't really doing anything all that IATI specific, but it does expect to be getting IATI data. 
As Ben says it could be made to detect and deal with datastore XML output.

It could probably be done fairly easily.

**Comment by stevieflow** [comment]
It would be useful if the Preview tool could preview datastore outputs I think.  Can this Issue become a task?

**Comment by caprenter** [comment]
I've checked out the branch with the commit above on so you can test at preview.iatistandard.org.

Couple of things - this will break if the datastore output changes format.

I've made a design decision to just show the activities returned, so ignoring the results and query elements - this means it's an augmented view of datastore data, but an otherwise accurate view of other IATI format data (whether it validates or not etc)

This may or may not be a distinction that people care about.

**Comment by caprenter** [comment]
@stevieflow Can you test pls?

**Comment by stevieflow** [comment]
Great, thanks.  Tested

Maybe add a link to the datastore in the text:

> This is slightly modified view of raw data from the datastore

?

Thanks

**Comment by hayfield** [comment]
As per the [Roadmaps for IATI Technical Team Products](http://discuss.iatistandard.org/t/roadmaps-for-iati-technical-team-products/733), the Preview Tool is to be closed down and no new features will be added before that point.
